INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [29/Oct/2020 21:29:15] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/Oct/2020 21:29:15] "GET /favicon.ico HTTP/1.1" 404 -
ERROR:app:Exception on /explore_categories [GET]
Traceback (most recent call last):
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\MRG\Anaconda3\Mini-Amazon\app\routes.py", line 238, in explore_categories
    categories = Category.query.all()
NameError: name 'Category' is not defined
INFO:werkzeug:127.0.0.1 - - [29/Oct/2020 21:29:16] "GET /explore_categories HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [29/Oct/2020 21:31:10] "GET / HTTP/1.1" 200 -
ERROR:app:Exception on /explore_categories [GET]
Traceback (most recent call last):
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\MRG\Anaconda3\Mini-Amazon\app\routes.py", line 238, in explore_categories
    categories = Category.query.all()
NameError: name 'Category' is not defined
INFO:werkzeug:127.0.0.1 - - [29/Oct/2020 21:31:11] "GET /explore_categories HTTP/1.1" 500 -
ERROR:app:Exception on /seller_summary [GET]
Traceback (most recent call last):
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\MRG\Anaconda3\Mini-Amazon\app\routes.py", line 203, in seller_summary
    items = sellerItems(current_user)
  File "C:\Users\MRG\Anaconda3\Mini-Amazon\app\routes.py", line 207, in sellerItems
    items = seller.sells.all()
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\werkzeug\local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'sells'
INFO:werkzeug:127.0.0.1 - - [29/Oct/2020 21:39:07] "GET /seller_summary HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [29/Oct/2020 21:39:07] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [29/Oct/2020 21:39:11] "GET /seller_reviews HTTP/1.1" 200 -
