INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [22/Oct/2020 19:29:29] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2020 19:29:32] "GET /seller_reviews HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2020 19:29:33] "GET /4/add_seller_review HTTP/1.1" 200 -
INFO:root:User (id: 1, username: test) added review for Seller (id: 4, username: test3) on 10/22/2020
INFO:werkzeug:127.0.0.1 - - [22/Oct/2020 19:29:46] "POST /4/add_seller_review HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2020 19:29:58] "GET /seller_reviews HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2020 19:29:59] "GET /5/add_seller_review HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2020 19:30:00] "GET /seller_reviews HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2020 19:30:01] "GET /4/add_seller_review HTTP/1.1" 200 -
ERROR:app:Exception on /seller_summary [GET]
Traceback (most recent call last):
  File "/Users/caleb1/Desktop/Comp Sci 316/Mini-Amazon/316_Amazon/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/caleb1/Desktop/Comp Sci 316/Mini-Amazon/316_Amazon/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/caleb1/Desktop/Comp Sci 316/Mini-Amazon/316_Amazon/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/caleb1/Desktop/Comp Sci 316/Mini-Amazon/316_Amazon/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/caleb1/Desktop/Comp Sci 316/Mini-Amazon/316_Amazon/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/caleb1/Desktop/Comp Sci 316/Mini-Amazon/316_Amazon/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/caleb1/Desktop/Comp Sci 316/Mini-Amazon/app/routes.py", line 143, in seller_summary
    items = sellerItems(current_user)
  File "/Users/caleb1/Desktop/Comp Sci 316/Mini-Amazon/app/routes.py", line 147, in sellerItems
    items = seller.sells.all()
  File "/Users/caleb1/Desktop/Comp Sci 316/Mini-Amazon/316_Amazon/lib/python3.8/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'sells'
INFO:werkzeug:127.0.0.1 - - [22/Oct/2020 19:30:16] "GET /seller_summary HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2020 19:30:37] "GET /index HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2020 19:30:42] "GET /1/item HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2020 19:30:45] "GET /index HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2020 19:30:46] "GET /seller_reviews HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2020 19:30:47] "GET /index HTTP/1.1" 200 -
