INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [02/Nov/2020 15:29:24] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Nov/2020 15:29:24] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [02/Nov/2020 15:29:24] "GET /explore_categories HTTP/1.1" 200 -
ERROR:app:Exception on /category/Groceries [GET]
Traceback (most recent call last):
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\MRG\Anaconda3\envs\CS316\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: category() got an unexpected keyword argument 'name'
INFO:werkzeug:127.0.0.1 - - [02/Nov/2020 15:29:26] "GET /category/Groceries HTTP/1.1" 500 -
